version: "3.8"

services:
  db:
    image: postgres:15
    container_name: crypto_alert_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto_alert_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    image: flyway/flyway:latest
    build: .
    container_name: crypto_alert_bot
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      USER: postgres
      PASSWORD: postgres
      HOST: db
      PORT: 5432
      NAME: crypto_alert_db
      SCHEMA: crypto_alerts
      TABLE_ALERTS: alerts
      TABLE_CONFIGS: configs
    command: >
      -url=jdbc:postgresql://db:5432/crypto_alert_db
      -user=postgres
      -password=postgres
      migrate

volumes:
  db_data: